# Generated by Django 4.1.1 on 2022-10-18 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_likepost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='no_likes',
            new_name='no_of_likes',
        ),
    ]
